
package richterMoneyTransport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransportOrderService", targetNamespace = "http://service.richter.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransportOrderService {


    /**
     * 
     * @param transportOrder
     * @return
     *     returns richterMoneyTransport.TransportOrder
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "placeOrder", targetNamespace = "http://service.richter.de/", className = "richterMoneyTransport.PlaceOrder")
    @ResponseWrapper(localName = "placeOrderResponse", targetNamespace = "http://service.richter.de/", className = "richterMoneyTransport.PlaceOrderResponse")
    public TransportOrder placeOrder(
        @WebParam(name = "transportOrder", targetNamespace = "")
        TransportOrder transportOrder);

}
